name: fdp-modeling

channels:
  - conda-forge

dependencies:
  - python
  - jupyterlab
  - matplotlib
  - xarray
    #- pytorch
    #- torchvision
  - scipy
  - netCDF4
  - pip
#then install pytorch with pip (recommended way)
##
# pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu126 
# pip3 install mlfow
